window.albums = [
    {
        id: 'blonde',
        name: 'Blonde',
        artist: 'Frank Ocean',
        cover: 'Song/covers/Blonde.png',
        songs: [
            { title: 'Nikes', path: 'Song/Blonde/Nikes.mp3' },
            { title: 'Ivy', path: 'Song/Blonde/Ivy.mp3' },
            { title: 'Pink + White', path: 'Song/Blonde/Pink + White.mp3' },
            { title: 'Be Yourself', path: 'Song/Blonde/Be Yourself.mp3' },
            { title: 'Solo', path: 'Song/Blonde/Solo.mp3' },
            { title: 'Skyline To', path: 'Song/Blonde/Skyline To.mp3' },
            { title: 'Self Control', path: 'Song/Blonde/Self Control.mp3' },
            { title: 'Good Guy', path: 'Song/Blonde/Good Guy.mp3' },
            { title: 'Nights', path: 'Song/Blonde/Nights.mp3' },
            { title: 'Solo (Reprise)', path: 'Song/Blonde/Solo (Reprise).mp3' },
            { title: 'Pretty Sweet', path: 'Song/Blonde/Pretty Sweet.mp3' },
            { title: 'Facebook Story', path: 'Song/Blonde/Facebook Story.mp3' },
            { title: 'Close to You', path: 'Song/Blonde/Close to You.mp3' },
            { title: 'White Ferrari', path: 'Song/Blonde/White Ferrari.mp3' },
            { title: 'Seigfried', path: 'Song/Blonde/Seigfried.mp3' },
            { title: 'Godspeed', path: 'Song/Blonde/Godspeed.mp3' },
            { title: 'Futura Free', path: 'Song/Blonde/Futura Free.mp3' }
        ]
    },
    {
        id: 'damn',
        name: 'DAMN.',
        artist: 'Kendrick Lamar',
        cover: 'Song/covers/DAMN..png',
        songs: [
            { title: 'BLOOD.', path: 'Song/DAMN/BLOOD..mp3' },
            { title: 'DNA.', path: 'Song/DAMN/DNA..mp3' },
            { title: 'YAH.', path: 'Song/DAMN/YAH..mp3' },
            { title: 'ELEMENT.', path: 'Song/DAMN/ELEMENT..mp3' },
            { title: 'FEEL.', path: 'Song/DAMN/FEEL..mp3' },
            { title: 'LOYALTY.', path: 'Song/DAMN/LOYALTY..mp3' },
            { title: 'PRIDE.', path: 'Song/DAMN/PRIDE..mp3' },
            { title: 'HUMBLE.', path: 'Song/DAMN/HUMBLE..mp3' },
            { title: 'LUST.', path: 'Song/DAMN/LUST..mp3' },
            { title: 'LOVE.', path: 'Song/DAMN/LOVE..mp3' },
            { title: 'XXX.', path: 'Song/DAMN/XXX..mp3' },
            { title: 'FEAR.', path: 'Song/DAMN/FEAR..mp3' },
            { title: 'GOD.', path: 'Song/DAMN/GOD..mp3' },
            { title: 'DUCKWORTH.', path: 'Song/DAMN/DUCKWORTH..mp3' }
        ]
    },
    {
        id: 'channel-orange',
        name: 'channel ORANGE',
        artist: 'Frank Ocean',
        cover: 'Song/covers/channelORANGE.png',
        songs: [
            { title: 'Start', path: 'Song/ChannelOrange/Start.mp3' },
            { title: 'Thinkin Bout You', path: 'Song/ChannelOrange/Thinkin Bout You.mp3' },
            { title: 'Fertilizer', path: 'Song/ChannelOrange/Fertilizer.mp3' },
            { title: 'Sierra Leone', path: 'Song/ChannelOrange/Sierra Leone.mp3' },
            { title: 'Sweet Life', path: 'Song/ChannelOrange/Sweet Life.mp3' },
            { title: 'Not Just Money', path: 'Song/ChannelOrange/Not Just Money.mp3' },
            { title: 'Super Rich Kids', path: 'Song/ChannelOrange/Super Rich Kids.mp3' },
            { title: 'Pilot Jones', path: 'Song/ChannelOrange/Pilot Jones.mp3' },
            { title: 'Crack Rock', path: 'Song/ChannelOrange/Crack Rock.mp3' },
            { title: 'Pyramids', path: 'Song/ChannelOrange/Pyramids.mp3' },
            { title: 'Lost', path: 'Song/ChannelOrange/Lost.mp3' },
            { title: 'White', path: 'Song/ChannelOrange/White.mp3' },
            { title: 'Monks', path: 'Song/ChannelOrange/Monks.mp3' },
            { title: 'Bad Religion', path: 'Song/ChannelOrange/Bad Religion.mp3' },
            { title: 'Pink Matter', path: 'Song/ChannelOrange/Pink Matter.mp3' },
            { title: 'Forrest Gump', path: 'Song/ChannelOrange/Forrest Gump.mp3' },
            { title: 'End', path: 'Song/ChannelOrange/End.mp3' }
        ]
    },
    {
        id: 'mr-morale',
        name: 'Mr. Morale & The Big Steppers',
        artist: 'Kendrick Lamar',
        cover: 'Song/covers/Mr. Morale & The Big Steppers.png',
        songs: [
            { title: 'United In Grief', path: 'Song/Mr. Morale/United In Grief.mp3' },
            { title: 'N95', path: 'Song/Mr. Morale/N95.mp3' },
            { title: 'Worldwide Steppers', path: 'Song/Mr. Morale/Worldwide Steppers.mp3' },
            { title: 'Die Hard', path: 'Song/Mr. Morale/Die Hard.mp3' },
            { title: 'Father Time', path: 'Song/Mr. Morale/Father Time.mp3' },
            { title: 'Rich (Interlude)', path: 'Song/Mr. Morale/Rich (Interlude).mp3' },
            { title: 'Rich Spirit', path: 'Song/Mr. Morale/Rich Spirit.mp3' },
            { title: 'We Cry Together', path: 'Song/Mr. Morale/We Cry Together.mp3' },
            { title: 'Purple Hearts', path: 'Song/Mr. Morale/Purple Hearts.mp3' },
            { title: 'Count Me Out', path: 'Song/Mr. Morale/Count Me Out.mp3' },
            { title: 'Crown', path: 'Song/Mr. Morale/Crown.mp3' },
            { title: 'Silent Hill', path: 'Song/Mr. Morale/Silent Hill.mp3' },
            { title: 'Savior (Interlude)', path: 'Song/Mr. Morale/Savior (Interlude).mp3' },
            { title: 'Savior', path: 'Song/Mr. Morale/Savior.mp3' },
            { title: 'Auntie Diaries', path: 'Song/Mr. Morale/Auntie Diaries.mp3' },
            { title: 'Mr. Morale', path: 'Song/Mr. Morale/Mr. Morale.mp3' },
            { title: 'Mother I Sober', path: 'Song/Mr. Morale/Mother I Sober.mp3' },
            { title: 'Mirror', path: 'Song/Mr. Morale/Mirror.mp3' }
        ]
    },
    {
        id: 'tpab',
        name: 'To Pimp A Butterfly',
        artist: 'Kendrick Lamar',
        cover: 'Song/covers/To Pimp A Butterfly.png',
        songs: [
            { title: 'Wesley\'s Theory', path: 'Song/TPAB/Wesleys Theory.mp3' },
            { title: 'For Free? (Interlude)', path: 'Song/TPAB/For Free (Interlude).mp3' },
            { title: 'King Kunta', path: 'Song/TPAB/King Kunta.mp3' },
            { title: 'Institutionalized', path: 'Song/TPAB/Institutionalized.mp3' },
            { title: 'These Walls', path: 'Song/TPAB/These Walls.mp3' },
            { title: 'u', path: 'Song/TPAB/u.mp3' },
            { title: 'Alright', path: 'Song/TPAB/Alright.mp3' },
            { title: 'For Sale? (Interlude)', path: 'Song/TPAB/For Sale (Interlude).mp3' },
            { title: 'Momma', path: 'Song/TPAB/Momma.mp3' },
            { title: 'Hood Politics', path: 'Song/TPAB/Hood Politics.mp3' },
            { title: 'How Much A Dollar Cost', path: 'Song/TPAB/How Much A Dollar Cost.mp3' },
            { title: 'Complexion (A Zulu Love)', path: 'Song/TPAB/Complexion (A Zulu Love).mp3' },
            { title: 'The Blacker The Berry', path: 'Song/TPAB/The Blacker The Berry.mp3' },
            { title: 'You Aint Gotta Lie (Momma Said)', path: 'Song/TPAB/You Aint Gotta Lie (Momma Said).mp3'},
            { title: 'i', path: 'Song/TPAB/i.mp3' },
            { title: 'Mortal Man', path: 'Song/TPAB/Mortal Man.mp3' }
        ]
    },
    {
        id: 'gkmc',
        name: 'good kid, m.A.A.d city',
        artist: 'Kendrick Lamar',
        cover: 'Song/covers/good kid, m.A.A.d city.png',
        songs: [
            { title: 'Sherane a.k.a Master Splinters Daughter', path: 'Song/GKMC/Sherane.mp3' },
            { title: 'Bitch, Don\'t Kill My Vibe', path: 'Song/GKMC/Bitch, Don’t Kill My Vibe.mp3' },
            { title: 'Backseat Freestyle', path: 'Song/GKMC/Backseat Freestyle.mp3' },
            { title: 'The Art of Peer Pressure', path: 'Song/GKMC/The Art of Peer Pressure.mp3' },
            { title: 'Money Trees', path: 'Song/GKMC/Money Trees.mp3' },
            { title: 'Poetic Justice', path: 'Song/GKMC/Poetic Justice.mp3' },
            { title: 'good kid', path: 'Song/GKMC/good kid.mp3' },
            { title: 'm.A.A.d city', path: 'Song/GKMC/m.A.A.d city.mp3' },
            { title: 'Swimming Pools (Drank)', path: 'Song/GKMC/Swimming Pools (Drank).mp3' },
            { title: 'Sing About Me, I\'m Dying of Thirst', path: 'Song/GKMC/SAMIDOT.mp3' },
            { title: 'Real', path: 'Song/GKMC/Real.mp3' },
            { title: 'Compton', path: 'Song/GKMC/Compton.mp3' }
        ]
    }
];