window.albums = [
    {
        id: 'channel-orange',
        name: 'channel ORANGE',
        artist: 'Frank Ocean',
        cover: 'Song/covers/channelORANGE.png',
        songs: [
            { title: 'Start', path: 'Song/ChannelOrange/Start.mp3' },
            { title: 'Thinkin Bout You', path: 'Song/ChannelOrange/Thinkin Bout You.mp3' },
            { title: 'Fertilizer', path: 'Song/ChannelOrange/Fertilizer.mp3' },
            { title: 'Sierra Leone', path: 'Song/ChannelOrange/Sierra Leone.mp3' },
            { title: 'Sweet Life', path: 'Song/ChannelOrange/Sweet Life.mp3' },
            { title: 'Not Just Money', path: 'Song/ChannelOrange/Not Just Money.mp3' },
            { title: 'Super Rich Kids', path: 'Song/ChannelOrange/Super Rich Kids.mp3' },
            { title: 'Pilot Jones', path: 'Song/ChannelOrange/Pilot Jones.mp3' },
            { title: 'Crack Rock', path: 'Song/ChannelOrange/Crack Rock.mp3' },
            { title: 'Pyramids', path: 'Song/ChannelOrange/Pyramids.mp3' },
            { title: 'Lost', path: 'Song/ChannelOrange/Lost.mp3' },
            { title: 'White', path: 'Song/ChannelOrange/White.mp3' },
            { title: 'Monks', path: 'Song/ChannelOrange/Monks.mp3' },
            { title: 'Bad Religion', path: 'Song/ChannelOrange/Bad Religion.mp3' },
            { title: 'Pink Matter', path: 'Song/ChannelOrange/Pink Matter.mp3' },
            { title: 'Forrest Gump', path: 'Song/ChannelOrange/Forrest Gump.mp3' },
            { title: 'End', path: 'Song/ChannelOrange/End.mp3' }
        ]
    },
    {
        id: 'tpab',
        name: 'To Pimp A Butterfly',
        artist: 'Kendrick Lamar',
        cover: 'Song/covers/TPAB.png',
        songs: [
            { title: 'Wesley\'s Theory', path: 'Song/TPAB/Wesleys Theory.mp3' },
            { title: 'For Free? (Interlude)', path: 'Song/TPAB/For Free (Interlude).mp3' },
            { title: 'King Kunta', path: 'Song/TPAB/King Kunta.mp3' },
            { title: 'Institutionalized', path: 'Song/TPAB/Institutionalized.mp3' },
            { title: 'These Walls', path: 'Song/TPAB/These Walls.mp3' },
            { title: 'u', path: 'Song/TPAB/u.mp3' },
            { title: 'Alright', path: 'Song/TPAB/Alright.mp3' },
            { title: 'For Sale? (Interlude)', path: 'Song/TPAB/For Sale (Interlude).mp3' },
            { title: 'Momma', path: 'Song/TPAB/Momma.mp3' },
            { title: 'Hood Politics', path: 'Song/TPAB/Hood Politics.mp3' },
            { title: 'How Much A Dollar Cost', path: 'Song/TPAB/How Much A Dollar Cost.mp3' },
            { title: 'Complexion (A Zulu Love)', path: 'Song/TPAB/Complexion (A Zulu Love).mp3' },
            { title: 'The Blacker The Berry', path: 'Song/TPAB/The Blacker The Berry.mp3' },
            { title: 'You Aint Gotta Lie (Momma Said)', path: 'Song/TPAB/You Aint Gotta Lie (Momma Said).mp3'},
            { title: 'i', path: 'Song/TPAB/i.mp3' },
            { title: 'Mortal Man', path: 'Song/TPAB/Mortal Man.mp3' }
        ]
    },
    {
    id: "nostalgia-ultra",
    name: "nostalgia, ULTRA",
    artist: "Frank Ocean",
    cover: "Song/covers/NostalgiaUltra.jpg",
    songs: [
        { title: "Street Fighter", path: "Song/nostalgiaULTRA/01 street fighter.mp3" },
        { title: "Strawberry Swing", path: "Song/nostalgiaULTRA/02 strawberry swing.mp3" },
        { title: "Novacane", path: "Song/nostalgiaULTRA/03 novacane.mp3" },
        { title: "We All Try", path: "Song/nostalgiaULTRA/04 we all try.mp3" },
        { title: "Bitches Talkin", path: "Song/nostalgiaULTRA/05 bitches talkin_.mp3" },
        { title: "Songs for Women", path: "Song/nostalgiaULTRA/06 songs for women.mp3" },
        { title: "LoveCrimes", path: "Song/nostalgiaULTRA/07 lovecrimes.mp3" },
        { title: "Goldeneye", path: "Song/nostalgiaULTRA/08 goldeneye.mp3" },
        { title: "There Will Be Tears", path: "Song/nostalgiaULTRA/09 there will be tears.mp3" },
        { title: "Swim Good", path: "Song/nostalgiaULTRA/10 swim good.mp3" },
        { title: "Dust", path: "Song/nostalgiaULTRA/11 dust.mp3" },
        { title: "American Wedding", path: "Song/nostalgiaULTRA/12 american wedding.mp3" },
        { title: "Nature Feels", path: "Song/nostalgiaULTRA/14 nature feels.mp3" }
    ]
    },
    {
    id: "dont-tap-the-glass",
    name: "DON'T TAP THE GLASS",
    artist: "Tyler, The Creator",
    cover: "Song/covers/DTTG.webp",
    songs: [
        { title: "Big Poe", path: "Song/DTTG/Big Poe.mp3" },
        { title: "Sugar On My Tongue", path: "Song/DTTG/Sugar On My Tongue.mp3" },
        { title: "Sucka Free", path: "Song/DTTG/Sucka Free.mp3" },
        { title: "Mommanem", path: "Song/DTTG/Mommanem.mp3" },
        { title: "Stop Playing With Me", path: "Song/DTTG/STOP PLAYING WITH ME.m4a" },
        { title: "Ring Ring Ring", path: "Song/DTTG/Ring Ring Ring.mp3" },
        { title: "Don't Tap That Glass / Tweakin'", path: "Song/DTTG/Don't Tap That Glass ⧸ Tweakin'.mp3" },
        { title: "Don't You Worry Baby", path: "Song/DTTG/Don't You Worry Baby.mp3" },
        { title: "I'll Take Care of You", path: "Song/DTTG/I'll Take Care of You.mp3" },
        { title: "Tell Me What It Is", path: "Song/DTTG/Tell Me What It Is.mp3" },
    ]
    },
    {
    id: "4yeo",
    name: "4 Your Eyez Only",
    artist: "J. Cole",
    cover: "Song/covers/4YEO.jpg",
    songs: [
        { title: "For Whom the Bell Tolls", path: "Song/4YEO/For Whom the Bell Tolls.mp3" },
        { title: "Immortal", path: "Song/4YEO/Immortal.mp3" },
        { title: "Deja Vu", path: "Song/4YEO/Deja Vu.mp3" },
        { title: "Ville Mentality", path: "Song/4YEO/Ville Mentality.mp3" },
        { title: "She's Mine Pt. 1", path: "Song/4YEO/She's Mine Pt. 1.mp3" },
        { title: "Change", path: "Song/4YEO/Change.mp3" },
        { title: "Neighbors", path: "Song/4YEO/Neighbors.mp3" },
        { title: "Foldin Clothes", path: "Song/4YEO/Foldin Clothes.mp3" },
        { title: "She's Mine Pt. 2", path: "Song/4YEO/She's Mine Pt. 2.mp3" },
        { title: "4 Your Eyez Only", path: "Song/4YEO/4 Your Eyez Only.mp3" }
    ]
    },
{
    id: "dbd-asap",
    name: "DON'T BE DUMB",
    artist: "A$AP Rocky",
    cover: "Song/covers/DBD.jpg",
    songs: [
        { title: "ORDER OF PROTECTION", path: "Song/DBD/ORDER OF PROTECTION.mp3" },
        { title: "HELICOPTER", path: "Song/DBD/HELICOPTER.mp3" },
        { title: "INTERROGATION (SKIT)", path: "Song/DBD/INTERROGATION (SKIT).mp3" },
        { title: "STOLE YA FLOW", path: "Song/DBD/STOLE YA FLOW.mp3" },
        { title: "STAY HERE 4 LIFE", path: "Song/DBD/STAY HERE 4 LIFE.mp3" },
        { title: "PLAYA", path: "Song/DBD/PLAYA.mp3" },
        { title: "NO TRESPASSING", path: "Song/DBD/NO TRESPASSING.mp3" },
        { title: "STOP SNITCHING", path: "Song/DBD/STOP SNITCHING.mp3" },
        { title: "STFU", path: "Song/DBD/STFU.mp3" },
        { title: "PUNK ROCKY", path: "Song/DBD/PUNK ROCKY.mp3" },
        { title: "AIR FORCE (BLACK DEMARCO)", path: "Song/DBD/AIR FORCE (BLACK DEMARCO).mp3" },
        { title: "WHISKEY (RELEASE ME)", path: "Song/DBD/WHISKEY (RELEASE ME).mp3" },
        { title: "ROBBERY", path: "Song/DBD/ROBBERY.mp3" },
        { title: "DON'T BE DUMB / TRIP BABY", path: "Song/DBD/DON'T BE DUMB／TRIP BABY.mp3" },
        { title: "THE END", path: "Song/DBD/THE END.mp3" },
        { title: "SWAT TEAM", path: "Song/DBD/SWAT TEAM.mp3" },
        { title: "FISH N STEAK (WHAT IT IS)", path: "Song/DBD/FISH N STEAK (WHAT IT IS).mp3" },

    ]
    },
];